import { ArrowUpRight, CheckCircle2 } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Hero } from "@/components/Hero";
import { PricingSection } from "@/components/PricingSection";
import { Footer } from "@/components/Footer";
import { ConsultationButton } from "@/components/ConsultationModal";

export default function Home() {
  return <><Navbar /><main><Hero /><PricingSection /><section className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#14845e]">A straightforward process</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-0.04em] text-[#081624] sm:text-5xl">Clear advice before you commit.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[["01", "Share your goal", "Tell us where you are and what you want to unlock."], ["02", "Get a route", "Receive practical next steps and transparent scope."], ["03", "Act with confidence", "Use your own authentic information to move forward."]].map(([number, title, text]) => <div key={number} className="rounded-2xl border border-slate-200 bg-[#fbfcfb] p-5"><span className="text-xs font-bold text-[#14845e]">{number}</span><h3 className="mt-4 font-display text-lg font-semibold text-[#081624]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></section><section className="bg-[#f5f7f4] px-5 py-20 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 overflow-hidden rounded-[1.75rem] bg-[#102335] p-8 text-white sm:p-10 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-300">Ready when you are</p><h2 className="mt-3 font-display text-3xl font-semibold leading-tight tracking-[-0.04em] sm:text-4xl">Bring us the problem behind the problem.</h2><p className="mt-3 text-base leading-7 text-slate-300">Start with a free quote, or book a focused consultation for Ksh 2,000/hr.</p><div className="mt-5 flex flex-wrap gap-4 text-sm text-slate-300"><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-brand-300" /> Direct WhatsApp workflow</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-brand-300" /> Authentic documents only</span></div></div><div className="flex shrink-0 flex-col gap-3 sm:flex-row"><ConsultationButton action="quote" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-brand-300 px-6 text-sm font-bold text-[#081624] transition hover:bg-brand-200">Request free quote <ArrowUpRight className="h-4 w-4" /></ConsultationButton><ConsultationButton className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/20 px-6 text-sm font-bold text-white transition hover:bg-white/10">Book consultation</ConsultationButton></div></div></section></main><Footer /></>;
}
